export const MOVIES = {
  GET_START: "MOVIES.GET_START",
  GET_SUCCESS: "MOVIES.GET_SUCCESS",
};

export const FILTERS = {
  IMB: "FILTERS.IMB",
  START_ALPHABET: "FILTERS.START_ALPHABET",
  END_ALPHABET: "FILTERS.END_ALPHABET",
  // ALL: "FILTERS.ALL",
};
